### ISSUE TITLE
Problems with multiple chat windows

### ISSUE THREAD

**Issue by tsiim** [Orukxu/SpamThrottle#4]
Hey,

I have 3 chat windows, with one having just world, trade and LFG. Turning SpamThrottle on, the messages are pushed only to the main chat window, if that window has the corresponding chats turned on but not to the other windows. Is this a bug or intended and can this be solved as a general thing, or could i get some help on how to modify the code to fit my case?

**Comment by Orukxu** [comment]
Hi Tslim,

Unfortunately this is a limitation of SpamThrottle in Vanilla. I haven't found a way to solve this issue; it has to do with how the chat handler is hooked in the early API. In TBC it is solvable, but that's not much help ofc. I'm still trying to find a solution. 

-- Mopar

**Comment by sipertruk** [comment]
Hello,

If I get this right the event handler is called : 
- once per chat frame for channel message, even for hidden frames, so that's 7 calls every time
- once per chat frame for other message type, if enabled in the frame

A simple way is to have one "unique message" table per chat frame.
I'm writing code to cover this here :
https://github.com/Orukxu/SpamThrottle/compare/master...sipertruk:multiframe?expand=1

**Comment by Orukxu** [comment]
Thanks for this, I’m taking a look!

**Comment by Orukxu** [comment]
OK looks to be doing exactly the right thing. I'm going to test it for a day or two, then will push this change to the master tree and update the version to 1.10. Thanks very much for this, solves a long standing problem that I haven't had time to investigate.
